subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 13
      leftFollower: 12
      rightMain: 14
      rightFollower: 15
    invertMotor:
      - rightMain
      - leftMain
  shooter:
    implemented: true
    talons:
      leftShooter: 2
      rightShooter: 3
    invertMotor:
      - rightShooter
      - leftShooter
constants:
  verbose: 0