subsystems:
    drivetrain:
        talons:
            leftMain: 17
            rightMain: 14
            leftFollower: 1
            rightFollower: 15
        invertMotor:
            - rightMain
    canon:
        implemented: false
        talons:
            mainShooter: 3
            mainFollower: 2
        invertMotor:
            - mainFollower

constants:
    verbose: 0
