subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 12
      leftFollower: 13
      rightMain: 14
      rightFollower: 15
    invertMotor:
      ##- rightMain
      ##- leftMain
constants:
  verbose: 0